### ISSUE TITLE
[Bug] [Windows]: ENOENT: no such file or directory, open 'C:\Users\USER\AppData\Roaming\SaladBind\Config/config.json'

### ISSUE THREAD

**Issue by eltrevii** [EvadeMaster/UnstableBind#8]
### Describe the bug

StableBind v1.8.2 (latest for the moment) throws an ENOENT error indicating that the file `config.json` was not found.

### Steps to reproduce

1. Download StableBind v1.8.2 (Vanilla) for Windows
2. Open `saladbind-win.exe`

### Expected behavior

No error is shown.

### Screenshots

![image](https://user-images.githubusercontent.com/59333567/210414638-ee21b29b-8677-49ab-8b83-f48b24a1c7d5.png)

### Device information

- OS: Windows 10 22H2, build 19045.2364
- Architecture: x64
- App version: 1.8.2

**Comment by validcube** [comment]
Hello, I'm sorry for the delay, I have fixed the issue in [v1.8.3](https://github.com/EvadeMaster/UnstableBind/releases/tag/v1.8.3-Vanilla), happy using it! 

_Now that's all, I shall go to sleep after a long day of school._
